name: Hello World on Push to Main

on:
  push:
    branches:
      - main  # Triggers only on pushes to the main branch

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello World"
